name: CI
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: Create application.yml
      run: |
        mkdir -p ./server_9dokme/src/main/resources
        cd ./server_9dokme/src/main/resources
        # application.yml 파일 생성
        touch application.yml
        # GitHub Secrets에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.CI_APPLICATION }}" > application.yml
        
        # application.yml 파일 확인
        cat application.yml
      shell: bash
      
    - name: build
      run: |
        cd server_9dokme  # 서버 디렉토리로 이동
        chmod +x gradlew
        ./gradlew build -x test  # 테스트 제외하고 빌드
      shell: bash
